---
galaxy_info:
  role_name: fastpackages
  namespace: infra
  author: Guido Grazioli, Ranabir Chakraborty
  description: The role is used to install required packages into the system.
  company: Red Hat

  license: Apache License 2.0

  min_ansible_version: 2.15.0

  galaxy_tags:
    - java
    - rhbk
    - ansible
    - datagrid
    - packages

dependencies: []
