---
# data_grid variables
admin_pass: admin_password
user_accounts:
  - { name: 'admin', password: 'adminpassword', roles: 'admin' }
  - { name: 'rhsso', password: 'rhssopassword', roles: 'application' }

# data_grid default overrides
data_grid_keycloak_caches: True
data_grid_configure_firewalld: True
data_grid_keycloak_persistence: False
data_grid_offline_install: False
data_grid_jgroups_relay: True
data_grid_jgroups_relay_sites: "{{ regions }}"
data_grid_jgroups_discovery: TCPPING

data_grid_default_realm_tls: True
data_grid_keystore_path: /etc/pki/java/keystore.jks
data_grid_keystore_alias: "*{{ domain_name }}"

certificates_install_keystore: True

data_grid_bind_address: "{{ inventory_hostname }}{{ domain_name }}"
data_grid_url: "https://{{ inventory_hostname }}{{ domain_name }}:11222"

data_grid_version: 8.4.6
