---
- name: Playbook for installing prerequisites
  hosts: all
  vars:
    fastpackages_packages_list:
      - procps-ng
      - mailcap
      - unzip
      - firewalld
      - ca-certificates
      - python3-lxml
      - net-tools
      - python3-policycoreutils
      - policycoreutils-python-utils
      - "{{ jvm_package }}"

  pre_tasks:
    - name: Install fastpackages prerequisites
      ansible.builtin.include_role:
        name: infra.rhbk_ha_cluster.fastpackages

  tasks:
    - name: "Set SELinux to Permissive mode"
      ansible.builtin.command: "setenforce Permissive"
      become: yes
      changed_when: false
    - name: "Get FQDN"
      ansible.builtin.command: "hostname --fqdn"
      become: yes
      register: current_fqdn
      changed_when: false
    - name: "Set FQDN"
      ansible.builtin.command: "hostnamectl set-hostname --static {{ inventory_hostname }}{{ domain_name }}"
      become: yes
      when: current_fqdn.stdout != (inventory_hostname + domain_name)
      changed_when: true

  post_tasks:
    - name: Install certificates prerequisites
      ansible.builtin.include_role:
        name: infra.rhbk_ha_cluster.certificates
